name: Test
on:
  push:
    branches: [main]
  pull_request: {}
jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: stable
      - uses: ankane/setup-mariadb@v1
        with:
          database: test
      - name: install
        run: go install -v github.com/davecheney/pub
      - name: Init database
        run: |
          pub --log-sql --dsn runner@/test auto-migrate
      - name: Create instance
        run: |
          pub --log-sql --dsn runner@/test create-instance --domain example.com --title "Example" --description "An example domain" --admin-email admin@example.com
      - name: Create test account
        run: |
          pub --log-sql --dsn runner@/test create-account --name test --domain example.com --email test@example.com --password password
        