name: Test
on:
  push:
    branches: [main]
  pull_request: {}
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        database: [mariadb]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: stable
      - name: Install database 
        if: ${{ matrix.database == 'mariadb' }}
        uses: ankane/setup-mariadb@v1
        with:
          database: test
        run: |
          export PUB_DSN='runner@/test'
          echo "::set-env name=PUB_DSN::$PUB_DSN"
      - name: Install pub
        run: go install -v --tags ${{ matrix.database }} github.com/davecheney/pub
      - name: Init database
        run: |
          pub --log-sql --dsn $PUB_DSN auto-migrate
      - name: Create instance
        run: |
          pub --log-sql --dsn $PUB_DSN create-instance --domain example.com --title "Example" --description "An example domain" --admin-email admin@example.com
      - name: Create test account
        run: |
          pub --log-sql --dsn $PUB_DSN create-account --name test --domain example.com --email test@example.com --password password
        